### ISSUE TITLE
Please add device - wattmeter.

### ISSUE THREAD

**Issue by havrla** [unparagoned/njsTuya#32] opened 2020-09-24 13:03 UTC
Helooo,
Please add support for wattmeter.

No data Voltage, Current, Power....

cloudtuya { payload: { devices: [ [Object] ], scenes: [] },
cloudtuya header: { code: 'SUCCESS', payloadVersion: 1 } } +3s
cloudtuya [ { data: { online: true, state: false },
cloudtuya name: '2dinwattletr',
cloudtuya icon: 'https://images.tuyaeu.com/smart/product_icon/cz.png',
cloudtuya id: '02448046bcddc25938da',
cloudtuya dev_type: 'switch',
cloudtuya ha_type: 'switch' } ] +21ms
cloudtuya prefilter [{"data":{"online":true,"state":false},"name":"2dinwattletr","icon":"https://images.tuyaeu.com/smart/product_icon/cz.png","id":"02448046bcddc25938da","dev_type":"switch","ha_type":"switch"}] +14ms

I can provide a cloud account with a wattmeter connected.

Thankssss
Havrla@lhotkanet.cz

**Comment by unparagoned** [comment] 2020-11-09 17:51
Duplicate of https://github.com/unparagoned/cloudtuya/issues/10

**Closed as completed by unparagoned** 2020-11-09 17:51 UTC
